# Включенные директории для проверки
included:
  - URMock_iOS

# Исключенные директории и файлы
excluded:
  - Pods
  - DerivedData
  - .build
  - Tests

# Отключенные правила (которые слишком строгие или не подходят)
disabled_rules:
  - trailing_whitespace     # Пробелы в конце строки
  - todo                    # TODO комментарии
  - multiple_closures_with_trailing_closure  # Множественные замыкания с завершающим синтаксисом

# Включенные необязательные правила
opt_in_rules:
  - empty_count             # Использовать isEmpty вместо count == 0
  - empty_string            # Использовать isEmpty вместо string == ""
  - closure_spacing         # Пробелы внутри замыканий
  - explicit_init           # Избегать явных вызовов init()
  - force_unwrapping        # Избегать принудительной распаковки опционалов
  - redundant_nil_coalescing # Избегать лишних операторов объединения с nil
  - vertical_parameter_alignment_on_call # Вертикальное выравнивание параметров при вызове

# Настройка серьезности для конкретных правил
force_cast: error           # Принудительное приведение типов - ошибка
force_try: warning          # Принудительный try - предупреждение
force_unwrapping: error     # Принудительная распаковка - ошибка

# Настройка параметров правил
line_length:
  warning: 100              # Предупреждение при длине строки более 100 символов
  error: 140                # Ошибка при длине строки более 140 символов
  ignores_comments: true    # Игнорировать комментарии

function_body_length:
  warning: 60               # Предупреждение при длине тела функции более 60 строк
  error: 100                # Ошибка при длине более 100 строк

type_body_length:
  warning: 200              # Предупреждение при длине типа более 200 строк
  error: 300                # Ошибка при длине более 300 строк

file_length:
  warning: 500              # Предупреждение при длине файла более 250 строк
  error: 1000               # Ошибка при длине более 500 строк

cyclomatic_complexity:
  warning: 15               # Предупреждение при сложности больше 15
  error: 25                 # Ошибка при сложности больше 25

# Формат вывода предупреждений и ошибок
reporter: "xcode"           # Формат совместимый с Xcode
